sonar.organization=christianalfonsoromeromartinez-1
sonar.projectKey=ChristianAlfonsoRomeroMartinez_dvnaFDSI
sonar.projectName=DVNA FDSI
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,public/**,docs/**,**/*.md
sonar.sourceEncoding=UTF-8