name: SonarCloud Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: npm test || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: 'christianalfonsoromeromartinez-1'
          projectKey: 'ChristianAlfonsoRomeroMartinez_dvnaFDSI'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}